In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving augmented_dataset.csv to augmented_dataset.csv


In [ ]:
import io
augmented_df = pd.read_csv(io.BytesIO(uploaded['augmented_dataset.csv']))
augmented_df

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0     0.256326   0.999994   0.999996   0.999998  -0.833034  -0.999999   
1     0.258175   0.999986   0.999997   0.999998  -0.823635  -0.999998   
2     0.248179   0.999985   0.999997   0.999999  -0.819612  -0.999999   
3     0.250090   0.999988   0.999997   0.999997  -0.825182  -0.999999   
4     0.257886   0.999984   0.999998   0.999998  -0.830631  -0.999999   
..         ...        ...        ...        ...        ...        ...   
995   0.256314   0.999946   0.999993   0.999997  -0.823636  -0.999999   
996   0.257544   0.999930   0.999993   0.999996  -0.824776  -0.999996   
997   0.247608   0.999969   0.999997   0.999998  -0.819162  -0.999999   
998   0.254440   0.999980   0.999996   0.999996  -0.818537  -0.999997   
999   0.254736   0.999990   0.999999   0.999998  -0.825198  -0.999999   

     feature_6  feature_7  feature_8  feature_9  ...  feature_12  feature_13  \
0    -0.999999   0.999997   0.999996  -0.999999  ...    0.999999    0.999999   
1    -1.000000   0.999996   0.999997  -0.999999  ...    0.999999    0.999998   
2    -0.999999   0.999995   0.999994  -0.999997  ...    0.999997    0.999999   
3    -0.999999   0.999996   0.999995  -0.999998  ...    0.999994    0.999999   
4    -1.000000   0.999995   0.999992  -0.999999  ...    0.999998    0.999999   
..         ...        ...        ...        ...  ...         ...         ...   
995  -1.000000   0.999996   0.999991  -0.999999  ...    0.999993    0.999998   
996  -0.999999   0.999983   0.999989  -0.999997  ...    0.999998    0.999998   
997  -0.999997   0.999998   0.999990  -0.999998  ...    0.999996    1.000000   
998  -0.999998   0.999996   0.999990  -0.999997  ...    0.999999    0.999998   
999  -0.999999   0.999998   0.999995  -0.999999  ...    0.999997    0.999999   

     feature_14  feature_15  feature_16  feature_17  feature_18  feature_19  \
0      0.999999    0.999997   -0.115654    0.999998   -0.990106   -0.999997   
1      0.999998    0.999982   -0.116685    0.999997   -0.988065   -0.999998   
2      0.999997    0.999989   -0.117339    0.999999   -0.989967   -0.999997   
3      0.999997    0.999970   -0.118726    0.999997   -0.989740   -0.999994   
4      0.999999    0.999987   -0.115834    0.999997   -0.989337   -0.999998   
..          ...         ...         ...         ...         ...         ...   
995    0.999997    0.999970   -0.115318    0.999994   -0.989502   -0.999997   
996    0.999997    0.999974   -0.114165    0.999989   -0.988171   -0.999996   
997    0.999998    0.999985   -0.117353    0.999999   -0.988167   -0.999997   
998    0.999997    0.999991   -0.119681    0.999997   -0.987315   -0.999997   
999    0.999999    0.999984   -0.118772    0.999999   -0.989754   -0.999996   

     feature_20  feature_21  
0     -0.999996    0.155688  
1     -0.999996    0.146246  
2     -0.999994    0.154363  
3     -0.999995    0.161387  
4     -0.999995    0.153144  
..          ...         ...  
995   -0.999994    0.165825  
996   -0.999990    0.152456  
997   -0.999996    0.156727  
998   -0.999994    0.164273  
999   -0.999996    0.159608  

[1000 rows x 22 columns]

# **Deep Learning - LSTM**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical

X = augmented_df.drop(augmented_df.columns[-1], axis=1)  # Drop the last column
y = augmented_df[augmented_df.columns[-1]]  # Use the last column as the target variable

# Convert target variable to categorical (one-hot encoding)
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_one_hot = to_categorical(y_encoded)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Reshape the data for LSTM input
X_train_reshaped = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_reshaped = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

# Number of classes
num_classes = y_train.shape[1]  # Use the shape of y_train to determine the number of classes

# Build the LSTM model
model = Sequential()
model.add(LSTM(100, input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2]), return_sequences=True))
model.add(LSTM(50, return_sequences=False))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train_reshaped, y_train, epochs=50, batch_size=32, validation_data=(X_test_reshaped, y_test))

# Make predictions
y_pred_proba = model.predict(X_test_reshaped)
y_pred = np.argmax(y_pred_proba, axis=1)

# Evaluate the model
print("Accuracy:", accuracy_score(np.argmax(y_test, axis=1), y_pred))
print("Confusion Matrix:\n", confusion_matrix(np.argmax(y_test, axis=1), y_pred))

Epoch 1/50
25/25 [==============================] - 7s 51ms/step - loss: 6.9108 - accuracy: 0.0000e+00 - val_loss: 6.9190 - val_accuracy: 0.0000e+00
Epoch 2/50
25/25 [==============================] - 0s 12ms/step - loss: 6.8983 - accuracy: 0.0050 - val_loss: 6.9412 - val_accuracy: 0.0000e+00
Epoch 3/50
25/25 [==============================] - 1s 24ms/step - loss: 6.8841 - accuracy: 0.0100 - val_loss: 6.9727 - val_accuracy: 0.0000e+00
Epoch 4/50
25/25 [==============================] - 1s 30ms/step - loss: 6.8471 - accuracy: 0.0113 - val_loss: 7.0708 - val_accuracy: 0.0000e+00
Epoch 5/50
25/25 [==============================] - 1s 24ms/step - loss: 6.7342 - accuracy: 0.0075 - val_loss: 7.4714 - val_accuracy: 0.0000e+00
Epoch 6/50
25/25 [==============================] - 0s 19ms/step - loss: 6.5321 - accuracy: 0.0025 - val_loss: 8.1877 - val_accuracy: 0.0000e+00
Epoch 7/50
25/25 [==============================] - 1s 24ms/step - loss: 6.3452 - accuracy: 0.0025 - val_loss: 8.7596 - val_ac

# **SVM**

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC

X = augmented_df.drop(augmented_df.columns[-1], axis=1)  # Drop the last column
y = augmented_df[augmented_df.columns[-1]]  # Use the last column as the target variable

# Convert target variable to categorical (label encoding)
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the SVM model
svm_model = SVC(kernel='linear')  # You can change the kernel based on your problem

# Train the SVM model
svm_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = svm_model.predict(X_test_scaled)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.0
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# **ELM**

# **PCA-Adaboost-SVM**